### PR TITLE
Fixed typo Installting to Installing

### PR DESCRIPTION
**Pull request by roquesf**

### CODE REVIEW

**Comment by pecigonzalo** [comment]
Thanks for the fix, please properly capitalize the commit and the PR and ill merge it.

**Comment by roquesf** [comment]
Done

**Comment by pecigonzalo** [comment]
The commit seems to be still wrong `Fixed typo Installting > Installing`

**Comment by roquesf** [comment]
Maybe it was the caret >, removed it

**Comment by pecigonzalo** [comment]
@roquesf Its not the PR title, its the commit as mentioned before, the `>` is ok.

**Comment by pecigonzalo** [comment]
No worries, Ill squash merge it

**Pull request merged**
